### ISSUE TITLE
Reconstruction fails when input has a not even number of pixels

### ISSUE THREAD

**Issue by dveni** [tomography/tomocupy-cli#49]
Hello,

Trying to reconstruct a dataset with a not even number of pixels per projection (in this case, 545) I got the following error:
```bash
tomocupy recon --file-name single_projs30_Np545_ps1.1.hdf5 --nsino-per-chunk 4 --reconstruction-type try
2024-01-17 15:09:10,988 - Saving log at /home/daveni/logs/tomocupyfp16on_2024-01-17_15_09_10.log
2024-01-17 15:09:10,992 - Output: create_projections_rec/try_center/single_projs30_Np545_ps1.1.h/recon
2024-01-17 15:09:13,777 - Processing slice 272
Traceback (most recent call last):-------------------------| 2.0%
  File "/home/daveni/miniconda3/envs/tomocupy/bin/tomocupy", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/daveni/miniconda3/envs/tomocupy/lib/python3.11/site-packages/tomocupy/__main__.py", line 171, in main
    args._func(args)
  File "/home/daveni/miniconda3/envs/tomocupy/lib/python3.11/site-packages/tomocupy/__main__.py", line 50, in run_rec
    clpthandle.recon_try()
  File "/home/daveni/miniconda3/envs/tomocupy/lib/python3.11/site-packages/tomocupy/rec.py", line 292, in recon_try
    datat = self.cl_tomo_func.fbp_filter_center(datat, sht)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daveni/miniconda3/envs/tomocupy/lib/python3.11/site-packages/tomocupy/tomo_functions.py", line 151, in fbp_filter_center
    data[:] = tmp[:, :, self.ne//2-self.n//2:self.ne//2+self.n//2]
    ~~~~^^^
  File "cupy/_core/core.pyx", line 1592, in cupy._core.core._ndarray_base.__setitem__
  File "cupy/_core/_routines_indexing.pyx", line 50, in cupy._core._routines_indexing._ndarray_setitem
  File "cupy/_core/_routines_indexing.pyx", line 1026, in cupy._core._routines_indexing._scatter_op
  File "cupy/_core/_kernel.pyx", line 1312, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/internal.pyx", line 380, in cupy._core.internal._broadcast_core
ValueError: operands could not be broadcast together with shapes (4, 30, 544) (4, 30, 545)
```
I suspect that it's due to this floor division (but have not debugged properly): 
```python
data[:] = tmp[:, :, self.ne//2-self.n//2:self.ne//2+self.n//2]
```

I tested with a dataset with an even number of pixels in the projections and works as expected. Adding one pixel of padding or validating the data to raise an error with a message warning about this would be helpful.

**Comment by nikitinvv** [comment]
@dveni thanks for reporting the issue. TomocuPy works with multiple 2 sizes because otherwise there is a  reconstruction slowdown due to FFTs. I have just fixed it in [this](https://github.com/tomography/tomocupy/commit/142fa9c6f1c07d98484b341695260d5a35cc64df) commit of the develop branch by cropping data to the multiple of 2 size. The develop branch will be soon merged with the main branch, so as the new tomocupy version will be published in conda-forge. 
As a temporarily solution with the old code you can use option --end-column 544.

**Comment by dveni** [comment]
Great, thanks for the quick response!
